rvm:
- 2.1.2
- 2.1.5
- 2.2.5
- 2.3.3
notifications:
  irc:
    channels:
      - "irc.freenode.net#theodi"
    template:
      - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
